# Numpy Practice ///

In [1]:
import numpy as np

In [4]:
r1 = np.random.randint(-6, 6, size = 5)
r1

array([ 0,  2, -6, -1, -6])

In [6]:
n = np.absolute(r1)
n

array([0, 2, 6, 1, 6])

In [7]:
#  e^x
np.exp(n)

array([  1.        ,   7.3890561 , 403.42879349,   2.71828183,
       403.42879349])

In [10]:
np.exp2(n)
# NO exp10

array([ 1.,  4., 64.,  2., 64.])

In [11]:
np.log(n)

<ipython-input-11-f5fe72b14f06>:1: RuntimeWarning: divide by zero encountered in log
  np.log(n)


array([      -inf, 0.69314718, 1.79175947, 0.        , 1.79175947])

In [12]:
np.log(n+2)

array([0.69314718, 1.38629436, 2.07944154, 1.09861229, 2.07944154])

In [13]:
np.log2(n+2)

array([1.       , 2.       , 3.       , 1.5849625, 3.       ])

In [14]:
np.log10(n+2)

array([0.30103   , 0.60205999, 0.90308999, 0.47712125, 0.90308999])

In [18]:
#  lol ariana// cz vibin on moonlight rn
ariana = 1e9
binarySearchOn = np.log2
binarySearchOn(ariana)

29.897352853986263

In [21]:
ariana = np.array([1e9]).astype(np.int64)
ariana

array([1000000000], dtype=int64)

In [33]:
ariana = np.float64(1e9).astype(np.int64)
ariana

1000000000

In [38]:
ariana = np.arange(5)
dangerouswoman = np.empty(5)
# print(dangerouswoman)
np.multiply(ariana, 10, out = dangerouswoman)
print(dangerouswoman)

[ 0. 10. 20. 30. 40.]


In [40]:
ariana = np.arange(1, 10)
np.sum(ariana)

45

In [42]:
np.add.reduce(ariana)

45

In [44]:
np.add.accumulate(ariana)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

## Read aggregation fxn available in numpy
sum, prod, cumsum, sumprod

In [45]:
#  ufunc

In [46]:
def makeDangerous(x):
    return x * 10
makeDangerous = np.frompyfunc(makeDangerous, 1, 1) #1 input , 1 output
ariana = np.arange(10)
makeDangerous(ariana)

array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=object)

In [47]:
makeDangerous(ariana).astype(np.int64)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=int64)

In [49]:
makeDangerous(ariana).astype(np.str)

array(['0', '10', '20', '30', '40', '50', '60', '70', '80', '90'],
      dtype='<U2')

In [50]:
np.mean(ariana)

4.5

In [54]:
np.mean(makeDangerous(ariana).astype(np.int64))

45.0

In [58]:
np.mean(makeDangerous(ariana).astype(np.int64)).astype(np.int64)

45

In [60]:
# Look at this simple mistake can be made
# because its not np.float
np.mean(makeDangerous(ariana)).astype(np.int64)

AttributeError: 'float' object has no attribute 'astype'

In [61]:
np.std(ariana)

2.8722813232690143

In [63]:
lambda ariana : ariana * 10

<function __main__.<lambda>(ariana)>

In [65]:
ariana = np.arange(15)
np.where(ariana == 12)

(array([12], dtype=int32),)

In [67]:
ariana = np.random.randint(15, size = 17)
ariana

array([13,  4, 13,  9, 12,  9,  5,  5,  8, 10, 12, 14,  1,  4, 10,  0, 11])

In [68]:
np.where(ariana == 1)

(array([12], dtype=int32),)

In [71]:
ariana = np.random.randint(15, size = (2, 3, 4))
ariana

array([[[ 1,  6,  0,  0],
        [12, 10,  0, 11],
        [ 5,  5,  3, 11]],

       [[ 5,  7,  2, 10],
        [ 9, 10,  3,  5],
        [ 5, 11,  3, 14]]])

In [72]:
np.where(ariana == 5)

(array([0, 0, 1, 1, 1], dtype=int32),
 array([2, 2, 0, 1, 2], dtype=int32),
 array([0, 1, 0, 3, 0], dtype=int32))

In [73]:
np.where(ariana == 14)

(array([1], dtype=int32), array([2], dtype=int32), array([3], dtype=int32))

In [74]:
np.sort?


Signature: np.sort(a, axis=-1, kind=None, order=None)
Docstring:
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecified fields will still be used, in the order in which
    they come up in the dtype, to break ties.

Returns
-------
sorted_array : ndarray
    Array of the same type and shape as `a`.

See Also
--------
ndarray.sort : Method to sort an array in-place.
argsort : Indirect sort.
lexsort : Indirect stable sort on multiple keys.
searchsorted : Find elements in a sorted array.
partition : Partial sort.

Notes
-----
The various sorting algorithms are characterized by their average speed,
worst case performance, work space size, and whether they are stable. A
stable sort keeps items with the same key in the same relative
order. The four algorithms implemented in NumPy have the following
properties:

=========== ======= ============= ============ ========
   kind      speed   worst case    work space   stable
=========== ======= ============= ============ ========
'quicksort'    1     O(n^2)            0          no
'heapsort'     3     O(n*log(n))       0          no
'mergesort'    2     O(n*log(n))      ~n/2        yes
'timsort'      2     O(n*log(n))      ~n/2        yes
=========== ======= ============= ============ ========

.. note:: The datatype determines which of 'mergesort' or 'timsort'
   is actually used, even if 'mergesort' is specified. User selection
   at a finer scale is not currently available.

All the sort algorithms make temporary copies of the data when
sorting along any but the last axis.  Consequently, sorting along
the last axis is faster and uses less space than sorting along
any other axis.

The sort order for complex numbers is lexicographic. If both the real
and imaginary parts are non-nan then the order is determined by the
real parts except when they are equal, in which case the order is
determined by the imaginary parts.

Previous to numpy 1.4.0 sorting real and complex arrays containing nan
values led to undefined behaviour. In numpy versions >= 1.4.0 nan
values are sorted to the end. The extended sort order is:

  * Real: [R, nan]
  * Complex: [R + Rj, R + nanj, nan + Rj, nan + nanj]

where R is a non-nan real value. Complex values with the same nan
placements are sorted according to the non-nan part if it exists.
Non-nan values are sorted as before.

.. versionadded:: 1.12.0

quicksort has been changed to `introsort <https://en.wikipedia.org/wiki/Introsort>`_.
When sorting does not make enough progress it switches to
`heapsort <https://en.wikipedia.org/wiki/Heapsort>`_.
This implementation makes quicksort O(n*log(n)) in the worst case.

'stable' automatically chooses the best stable sorting algorithm
for the data type being sorted.
It, along with 'mergesort' is currently mapped to
`timsort <https://en.wikipedia.org/wiki/Timsort>`_
or `radix sort <https://en.wikipedia.org/wiki/Radix_sort>`_
depending on the data type.
API forward compatibility currently limits the
ability to select the implementation and it is hardwired for the different
data types.

.. versionadded:: 1.17.0

Timsort is added for better performance on already or nearly
sorted data. On random data timsort is almost identical to
mergesort. It is now used for stable sort while quicksort is still the
default sort if none is chosen. For timsort details, refer to
`CPython listsort.txt <https://github.com/python/cpython/blob/3.7/Objects/listsort.txt>`_.
'mergesort' and 'stable' are mapped to radix sort for integer data types. Radix sort is an
O(n) sort instead of O(n log n).

.. versionchanged:: 1.17.0

NaT now sorts to the end of arrays for consistency with NaN.

#### Sorting along rows and columns is known 

In [75]:
ariana = np.random.randint(10, size = 20)
ariana

array([1, 0, 9, 4, 1, 3, 0, 8, 1, 3, 8, 9, 6, 9, 0, 8, 4, 4, 0, 4])

In [76]:
ariana[ariana > 4]

array([9, 8, 8, 9, 6, 9, 8])

In [77]:
ariana > 4

array([False, False,  True, False, False, False, False,  True, False,
       False,  True,  True,  True,  True, False,  True, False, False,
       False, False])

In [83]:
ariana = np.random.randint(1e9, size = int(1e5))

In [91]:
%%time
ariana.argsort()

Wall time: 15.6 ms


array([49131, 22312, 81585, ..., 77661, 72092, 36693], dtype=int32)

In [92]:
%%time
np.argsort(ariana)

Wall time: 15.6 ms


array([49131, 22312, 81585, ..., 77661, 72092, 36693], dtype=int32)