# Numpy Practice //


In [1]:
import numpy as np

In [3]:
n = np.arange(36)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [6]:
n.reshape((6, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [8]:
n.reshape((6, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [9]:
n.reshape((7, -1))

ValueError: cannot reshape array of size 36 into shape (7,newaxis)

In [11]:
# returns a copy !
n.reshape((6, 6)).base

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [14]:
x = np.random.randint(10, size = (2, 5))
x

array([[6, 2, 8, 3, 1],
       [5, 8, 8, 9, 1]])

In [18]:
# Flatten array
x.reshape(-1)

array([6, 2, 8, 3, 1, 5, 8, 8, 9, 1])

In [19]:
# Transpose
x.T

array([[6, 5],
       [2, 8],
       [8, 8],
       [3, 9],
       [1, 1]])

np.rot90?

## Signature:
np.rot90(m, k=1, axes=(0, 1))
Docstring:
Rotate an array by 90 degrees in the plane specified by axes.

Rotation direction is from the first towards the second axis.

Parameters
----------
m : array_like
    Array of two or more dimensions.
k : integer
    Number of times the array is rotated by 90 degrees.
axes: (2,) array_like
    The array is rotated in the plane defined by the axes.
    Axes must be different.

    .. versionadded:: 1.12.0

Returns
-------
y : ndarray
    A rotated view of `m`.

See Also
--------
flip : Reverse the order of elements in an array along the given axis.
fliplr : Flip an array horizontally.
flipud : Flip an array vertically.

In [29]:
r1 = np.random.randint(10, size=(2, 3))
r1

array([[3, 5, 9],
       [4, 3, 6]])

In [30]:
np.rot90(r1)
r1

array([[3, 5, 9],
       [4, 3, 6]])

In [31]:
np.flip(r1)
r1

array([[3, 5, 9],
       [4, 3, 6]])

In [32]:
np.flip?

# Concatenate Array

In [35]:
n1 = np.random.randint(10, size = 5)
n1

array([4, 8, 4, 0, 0])

In [41]:
n2 = np.random.randint(10, 20, size=6)
n2

array([19, 10, 10, 10, 11, 16])

In [42]:
np.concatenate([n1, n2])

array([ 4,  8,  4,  0,  0, 19, 10, 10, 10, 11, 16])

In [45]:
n3 = np.random.randint(20, 30, size = 2)
n3

array([22, 27])

In [46]:
np.concatenate([n1, n2, n3])

array([ 4,  8,  4,  0,  0, 19, 10, 10, 10, 11, 16, 22, 27])

In [47]:
n1 = np.random.randint(10, size = (2, 2))
n1

array([[9, 7],
       [5, 2]])

In [48]:
n2 = np.random.randint(10, 20, size=(2, 2))
n2

array([[12, 14],
       [12, 17]])

In [49]:
np.concatenate([n1, n2])

array([[ 9,  7],
       [ 5,  2],
       [12, 14],
       [12, 17]])

In [51]:
np.concatenate([n1, n2], axis = 1)

array([[ 9,  7, 12, 14],
       [ 5,  2, 12, 17]])

In [52]:
# Dimensions should be equal

In [53]:
# 

In [54]:
np.hstack([n1, n2])

array([[ 9,  7, 12, 14],
       [ 5,  2, 12, 17]])

In [55]:
np.vstack([n1, n2])

array([[ 9,  7],
       [ 5,  2],
       [12, 14],
       [12, 17]])

In [56]:
# CHEcking Something next

In [57]:
np.hstack([n1, n2]) == np.concatenate([n1, n2], axis = 1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
np.hstack([n1, n2]) is np.concatenate([n1, n2], axis = 1)

False

In [61]:
n = np.arange(12)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
np.split(n, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [66]:
# np.split(n, 5)

# will throw an error cause equal partition

In [67]:
np.split?

### Try also hsplit and vsplit

In [68]:
n.dtype

dtype('int32')

In [69]:
n.astype('float')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [70]:
n.astype(np.float64)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [72]:
n.astype(np.string_)

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10',
       b'11'], dtype='|S11')

## Array Arithmetic is done like as done on each and every index

In [73]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [76]:
y = np.arange(4, 8)
y

array([4, 5, 6, 7])

In [77]:
x + y

array([ 4,  6,  8, 10])

In [78]:
x * y

array([ 0,  5, 12, 21])

In [79]:
x - y

array([-4, -4, -4, -4])

In [80]:
x / y

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [82]:
# error lol
y / x

<ipython-input-82-25264b4b68a5>:2: RuntimeWarning: divide by zero encountered in true_divide
  y / x


array([       inf, 5.        , 3.        , 2.33333333])

In [83]:
np.float("inf")

inf

In [84]:
-np.float("inf")

-inf

In [86]:
r1 = np.random.randint(10, size = (2, 5))
r1

array([[5, 0, 2, 8, 7],
       [8, 7, 9, 3, 0]])

In [98]:
r2 = np.random.randint(10, size = (2, 5))
r2

array([[8, 5, 2, 6, 0],
       [9, 6, 1, 3, 0]])

In [99]:
r1 + r2

array([[13,  5,  4, 14,  7],
       [17, 13, 10,  6,  0]])

In [100]:
r1 * r2

array([[40,  0,  4, 48,  0],
       [72, 42,  9,  9,  0]])

In [101]:
r1 > r2

array([[False, False, False,  True,  True],
       [False,  True,  True, False, False]])

In [102]:
r1[r1 > r2]

array([8, 7, 7, 9])